### ISSUE TITLE
Need to Identify Which Couchbase Instance is Causing the Error

### ISSUE THREAD

**Issue by kilicoglutuncay** [Trendyol/go-dcp-couchbase#18]
**Is your feature request related to a problem? Please describe.**
`panic: unambiguous timeout | {"InnerError":{"InnerError":{"InnerError":{},"Message":"unambiguous timeout"}},"OperationID":"WaitUntilReady","Opaque":"","TimeObserved":5000756985,"RetryReasons":["NOT_READY"],"RetryAttempts":10,"LastDispatchedTo":"","LastDispatchedFrom":"","LastConnectionID":"","Internal":{"ResourceUnits":null}}`

When **NewConnectorBuilder** sends an error, we can't determine whether the issue is with the source, target, or meta connection.

**Describe the solution you'd like**
We can resolve the issue by logging which connection caused the error.

**Comment by erayarslan** [comment]
need to move this improvement [Trendyol/go-dcp](https://github.com/Trendyol/go-dcp)

**Comment by erayarslan** [comment]
fixed with v1.1.54
